# Generated by Django 5.1.3 on 2024-11-29 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="requirements",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
