# Generated by Django 5.1.3 on 2024-11-28 22:09

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_remove_coursecontent_content_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="type",
            name="color",
            field=colorfield.fields.ColorField(
                default="#FFFFFFFF", image_field=None, max_length=25, samples=None
            ),
        ),
    ]
