# Generated by Django 5.1.3 on 2024-11-29 09:13

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_type_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="lesson",
            field=models.DecimalField(decimal_places=2, default="", max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="type",
            name="color",
            field=colorfield.fields.ColorField(
                default="#FFFFFF", image_field=None, max_length=25, samples=None
            ),
        ),
    ]
