# Generated by Django 5.1.3 on 2024-11-29 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_course_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="lessons_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="course",
            name="level",
            field=models.CharField(
                choices=[
                    ("Beginner", "Beginner"),
                    ("Intermediate", "Intermediate"),
                    ("Advanced", "Advanced"),
                    ("All Level", "All Level"),
                ],
                default="Beginner",
                max_length=20,
            ),
        ),
    ]
