# Generated by Django 5.1.3 on 2024-11-30 16:17

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_course_lessons_count_alter_course_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="image",
            field=models.ImageField(default="", upload_to=main.models.image_upload),
            preserve_default=False,
        ),
    ]
